FROM openjdk:11

RUN apt-get update \
    && apt-get install -y time

COPY logging.xml /root
COPY app/build/libs/app-all.jar /root/
COPY run_relay_server.sh /root/

# CMD ["/root/run_relay_server.sh"]
CMD ["sleep", "365d"]